---
driver:
  name: ec2

platforms:
  - name: aws-ec2-ubuntu
    image: ami-009c174642dba28e4
    instance_type: t2.micro
    vpc_subnet_id: subnet-a2efa1d9

provisioner:
  name: ansible
  playbooks:
    converge: ../converge.yml

verifier:
  name: testinfra
  directory: ../tests/
  env:
    # get rid of the DeprecationWarning messages of third-party libs,
    # see https://docs.pytest.org/en/latest/warnings.html#deprecationwarning-and-pendingdeprecationwarning
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    # show which tests where executed in test output
    v: 1
