driver:
  name: docker

platforms:
  - name: docker-ubuntu
    image: ubuntu:bionic
    privileged: true

provisioner:
  name: ansible
  playbooks:
    prepare: prepare-docker-in-docker.yml
    converge: ../converge.yml

verifier:
  name: testinfra
  directory: ../tests/
  env:
    # get rid of the DeprecationWarning messages of third-party libs,
    # see https://docs.pytest.org/en/latest/warnings.html#deprecationwarning-and-pendingdeprecationwarning
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    # show which tests where executed in test output
    v: 1