galaxy_info:
  author: jonashackt
  description: Role to install Docker on Ubuntu, continuously tested with Molecule on AWS EC2
  company: jonashackt.io
  license: license (MIT)

  min_ansible_version: 2.8

  # https://galaxy.ansible.com/api/v1/platforms/
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - bionic

  galaxy_tags:
    - docker
    - ubuntu
    - molecule
    - bionic
    - xenial

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
